import type { User, LearningCategory } from './types';

export const users: User[] = [
    { name: 'Gustavo', password: '9921', avatarUrl: 'https://placehold.co/100x100/E50914/FFFFFF?text=G' },
    { name: 'Yago', password: '8845', avatarUrl: 'https://placehold.co/100x100/1E40AF/FFFFFF?text=Y' },
    { name: 'Victor', password: '4975', avatarUrl: 'https://placehold.co/100x100/16A34A/FFFFFF?text=V' },
];

export const categories: LearningCategory[] = [
    {
        id: 'ia',
        title: 'Inteligência Artificial',
        description: 'Aprenda sobre IA, machine learning e como usar ferramentas de IA no dia a dia',
        icon: 'Fire',
        color: 'red',
        videos: [
            { id: 'a23_M-f4v8k', title: 'O que é INTELIGÊNCIA ARTIFICIAL?', duration: '15:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/a23_M-f4v8k/hqdefault.jpg' },
            { id: 'J_C6_zXg5pU', title: 'REDES NEURAIS: O que são e COMO FUNCIONAM?', duration: '18:22', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/J_C6_zXg5pU/hqdefault.jpg' },
            { id: '5F_zYh_IixM', title: 'Como Usar o CHATGPT DIREITO (e tirar o máximo dele)', duration: '20:10', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/5F_zYh_IixM/hqdefault.jpg' },
            { id: 'zgg_gG3a_I0', title: 'O ROBÔ que APRENDE SOZINHO (aprendizado por reforço)', duration: '12:45', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/zgg_gG3a_I0/hqdefault.jpg' },
            { id: '9J_2K0hT3bA', title: 'DEEP LEARNING: O que é e COMO FUNCIONA?', duration: '14:05', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/9J_2K0hT3bA/hqdefault.jpg' },
            { id: 'I3KVVGNv-6g', title: 'O Guia DEFINITIVO de PROMPTS para o ChatGPT', duration: '22:15', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/I3KVVGNv-6g/hqdefault.jpg' },
            { id: 'Lade-Da_aEw', title: 'Como usar o MIDJOURNEY (Guia completo para iniciantes)', duration: '31:40', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Lade-Da_aEw/hqdefault.jpg' },
            { id: '8m_k2B8nh3c', title: 'Machine Learning para INICIANTES (O que é e como começar?)', duration: '11:11', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/8m_k2B8nh3c/hqdefault.jpg' },
            { id: 'j1pCRYfT8sM', title: '7 IAs para AUTOMATIZAR seu TRABALHO', duration: '12:03', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/j1pCRYfT8sM/hqdefault.jpg' },
            { id: 'LQy_gmmph38', title: 'O que são LLMs? (Modelos de Linguagem Gigantes)', duration: '17:34', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/LQy_gmmph38/hqdefault.jpg' },
            { id: '0p-Y1R3fg_A', title: 'Inteligência Artificial que CRIA VÍDEOS (SORA)', duration: '13:50', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/0p-Y1R3fg_A/hqdefault.jpg' },
            { id: 'at-wDMPo_cE', title: 'Prompt Engineering: O guia para iniciantes.', duration: '19:42', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/at-wDMPo_cE/hqdefault.jpg' },
            { id: 'KxG2QdYJ5p4', title: 'Construí um GPT em 25 minutos', duration: '25:28', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/KxG2QdYJ5p4/hqdefault.jpg' },
            { id: 'iR6K-uh2-wY', title: 'O que é IA Generativa?', duration: '5:59', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/iR6K-uh2-wY/hqdefault.jpg' },
            { id: 'wY_Vz4d9wY4', title: 'As 10 IAs que você PRECISA CONHECER!', duration: '9:36', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/wY_Vz4d9wY4/hqdefault.jpg' },
        ],
    },
    {
        id: 'marketing-digital',
        title: 'Marketing Digital',
        description: 'Estratégias de marketing digital, redes sociais e vendas online',
        icon: 'Chart',
        color: 'orange',
        videos: [
            { id: '2uauNWnS_qQ', title: 'O que é TRÁFEGO PAGO? | O GUIA DEFINITIVO', duration: '25:11', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/2uauNWnS_qQ/hqdefault.jpg' },
            { id: 'tHjT-S4l-g8', title: 'AULA COMPLETA DE COPYWRITING (iniciantes)', duration: '40:37', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/tHjT-S4l-g8/hqdefault.jpg' },
            { id: 'l4y0qL9C4aM', title: 'GOOGLE ADS PARA INICIANTES: AULA COMPLETA 2024', duration: '1:05:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/l4y0qL9C4aM/hqdefault.jpg' },
            { id: 'hJg2qQoLi-U', title: 'SEO para INICIANTES: O que é e como OTIMIZAR seu SITE?', duration: '10:58', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/hJg2qQoLi-U/hqdefault.jpg' },
            { id: 'WJ2sYTyqMIs', title: 'FACEBOOK ADS (META ADS) PARA INICIANTES 2024', duration: '55:19', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/WJ2sYTyqMIs/hqdefault.jpg' },
            { id: 'w0Lage-4o_c', title: 'Como ser um GESTOR DE TRÁFEGO (Aula completa)', duration: '51:03', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/w0Lage-4o_c/hqdefault.jpg' },
            { id: 'Yl-4hP5Ab-E', title: 'MARKETING DIGITAL PARA INICIANTES | Guia completo', duration: '29:56', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Yl-4hP5Ab-E/hqdefault.jpg' },
            { id: 'Q3z-xYt-v5o', title: 'Os 7 Gatilhos Mentais Mais Poderosos para Vendas', duration: '15:23', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Q3z-xYt-v5o/hqdefault.jpg' },
            { id: 'tM2C-aX-M-c', title: 'Funil de Vendas no Marketing Digital: O que é e Como Criar?', duration: '22:18', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/tM2C-aX-M-c/hqdefault.jpg' },
            { id: '1uX6k6y-T-M', title: 'Como Vender no Instagram como Afiliado (Passo a Passo)', duration: '18:50', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/1uX6k6y-T-M/hqdefault.jpg' },
            { id: 'zI_a-HEL-NU', title: 'Como fazer REMARKETING (Google Ads)', duration: '15:10', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/zI_a-HEL-NU/hqdefault.jpg' },
            { id: 'ePlusCNu-3k', title: 'O que é Inbound Marketing? (Guia Para Iniciantes)', duration: '11:47', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/ePlusCNu-3k/hqdefault.jpg' },
            { id: 'oJua_f5IEgI', title: 'Como Anunciar no TikTok Ads (Passo a Passo)', duration: '40:48', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/oJua_f5IEgI/hqdefault.jpg' },
            { id: 'JqHel-dp9iM', title: 'AIDA: A Melhor Técnica de Copywriting Para Anúncios', duration: '13:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/JqHel-dp9iM/hqdefault.jpg' },
            { id: 'T2ejZACu2vM', title: 'Email Marketing para Iniciantes (Tutorial Completo)', duration: '28:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/T2ejZACu2vM/hqdefault.jpg' },
        ],
    },
    {
        id: 'mercado-financeiro',
        title: 'Mercado Financeiro',
        description: 'Investimentos, ações, criptomoedas e educação financeira',
        icon: 'Dollar',
        color: 'green',
        videos: [
            { id: 'LzMjJ0gQnZ8', title: 'COMO COMEÇAR A INVESTIR DO ZERO? O passo a passo COMPLETO!', duration: '33:15', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/LzMjJ0gQnZ8/hqdefault.jpg' },
            { id: 'l4eJmZo8HEY', title: 'AÇÕES PARA INICIANTES: O GUIA COMPLETO PARA COMEÇAR A INVESTIR', duration: '28:44', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/l4eJmZo8HEY/hqdefault.jpg' },
            { id: 's7zP2V7eW3Q', title: 'ANÁLISE TÉCNICA (GRÁFICA) PARA INICIANTES', duration: '21:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/s7zP2V7eW3Q/hqdefault.jpg' },
            { id: 'i_r0tI80kfY', title: 'O que é DAY TRADE? Como funciona para INICIANTES?', duration: '17:53', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/i_r0tI80kfY/hqdefault.jpg' },
            { id: 'Yurej405y_k', title: 'CRIPTOMOEDAS PARA INICIANTES: O GUIA COMPLETO!', duration: '45:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Yurej405y_k/hqdefault.jpg' },
            { id: 'u_8nK_432I8', title: 'PRICE ACTION para INICIANTES (Aula Completa)', duration: '48:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/u_8nK_432I8/hqdefault.jpg' },
            { id: 'b7Z2iA2_yq8', title: 'O que é SWING TRADE? E como funciona?', duration: '12:20', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/b7Z2iA2_yq8/hqdefault.jpg' },
            { id: 'zJz3l9L8y_E', title: 'FUNDOS IMOBILIÁRIOS (FIIs) para INICIANTES', duration: '19:45', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/zJz3l9L8y_E/hqdefault.jpg' },
            { id: 'fJkBT6E-e_s', title: 'Como Declarar IMPOSTO DE RENDA de Ações e FIIs', duration: '25:10', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/fJkBT6E-e_s/hqdefault.jpg' },
            { id: '7oA_mW21j-w', title: 'RENDA FIXA: O GUIA COMPLETO para Iniciantes!', duration: '33:51', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/7oA_mW21j-w/hqdefault.jpg' },
            { id: 'eGT-ZVg3fI8', title: 'Os 10 Erros Mais Comuns dos Investidores Iniciantes', duration: '14:28', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/eGT-ZVg3fI8/hqdefault.jpg' },
            { id: '2G02uC2a-aU', title: 'O Que É BITCOIN? (para iniciantes)', duration: '12:05', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/2G02uC2a-aU/hqdefault.jpg' },
            { id: 'p7GNoF-C_mM', title: 'Como MONTAR UMA CARTEIRA de INVESTIMENTOS do ZERO', duration: '17:39', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/p7GNoF-C_mM/hqdefault.jpg' },
            { id: 'pEdoD2cWifc', title: 'Análise FUNDAMENTALISTA de Ações (Passo a Passo)', duration: '29:55', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/pEdoD2cWifc/hqdefault.jpg' },
            { id: 'T2sEJQv4lA0', title: 'Como organizar sua vida financeira (Planilha Grátis)', duration: '11:41', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/T2sEJQv4lA0/hqdefault.jpg' },
        ],
    },
    {
        id: 'vendas-produtos-digitais',
        title: 'Vendas e Produtos Digitais',
        description: 'Aprenda a vender online, criar ebooks, infoprodutos e aumentar suas vendas',
        icon: 'Cart',
        color: 'blue',
        videos: [
            { id: 'Yusm3BrDF7Q', title: 'COMO VENDER NA HOTMART COMO AFILIADO EM 2024 (passo a passo)', duration: '38:29', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Yusm3BrDF7Q/hqdefault.jpg' },
            { id: 'u-T2K_KxGv0', title: 'O QUE É DROPSHIPPING? COMO FUNCIONA?', duration: '13:41', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/u-T2K_KxGv0/hqdefault.jpg' },
            { id: 'xL5b2bJvG-Y', title: 'COMO FAZER O SEU PRIMEIRO LANÇAMENTO DE PRODUTO DIGITAL', duration: '35:55', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/xL5b2bJvG-Y/hqdefault.jpg' },
            { id: 'oK2Jp_Z3q6o', title: 'PLR: O que é e como ganhar dinheiro com isso?', duration: '19:07', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/oK2Jp_Z3q6o/hqdefault.jpg' },
            { id: 'kX_mQ6T_t6Q', title: 'KIWIFY PARA INICIANTES 2024 (TUTORIAL COMPLETO)', duration: '22:18', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/kX_mQ6T_t6Q/hqdefault.jpg' },
            { id: 'cZiju38SA0g', title: 'Como CRIAR um INFOPRODUTO do ZERO (Passo a Passo)', duration: '23:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/cZiju38SA0g/hqdefault.jpg' },
            { id: 'KDM2_b2l4Sg', title: 'As 4 MELHORES Estratégias de VENDAS para Afiliados', duration: '17:42', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/KDM2_b2l4Sg/hqdefault.jpg' },
            { id: 'iMv30a-Yw_g', title: 'Como criar uma PÁGINA DE VENDAS que vende muito', duration: '30:25', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/iMv30a-Yw_g/hqdefault.jpg' },
            { id: '5q_3GvYn0M4', title: 'O que é um PRODUTOR DIGITAL? (Guia Completo)', duration: '14:50', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/5q_3GvYn0M4/hqdefault.jpg' },
            { id: '8aY8Mfl4w58', title: 'Como Usar o CANVA para Criar EBOOKS (Tutorial)', duration: '18:12', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/8aY8Mfl4w58/hqdefault.jpg' },
            { id: '5iBwSjQR34A', title: 'Como ESCOLHER UM BOM PRODUTO para vender (Hotmart)', duration: '16:05', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/5iBwSjQR34A/hqdefault.jpg' },
            { id: 'N17a5jSSeYQ', title: 'Fórmula de Lançamento: O que é e Como Funciona?', duration: '10:33', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/N17a5jSSeYQ/hqdefault.jpg' },
            { id: 'j-5EAKJ8KOQ', title: 'Como criar um CURSO ONLINE do ZERO', duration: '29:48', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/j-5EAKJ8KOQ/hqdefault.jpg' },
            { id: 'X50b-h74iB4', title: 'Como Vender Sem APARECER (Estratégias)', duration: '12:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/X50b-h74iB4/hqdefault.jpg' },
            { id: '2VTSmyeB_Oo', title: 'Como criar um E-commerce do ZERO (Passo a Passo)', duration: '45:11', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/2VTSmyeB_Oo/hqdefault.jpg' },
        ],
    },
    {
        id: 'ferramentas-automacao',
        title: 'Ferramentas e Automação',
        description: 'Domine Lovable, n8n, Make, Zapier e outras ferramentas de automação',
        icon: 'Wrench',
        color: 'indigo',
        videos: [
            { id: 's9c2YdMvJu4', title: 'N8N: O QUE É? E COMO USAR? (TUTORIAL COMPLETAÇO)', duration: '1:12:34', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/s9c2YdMvJu4/hqdefault.jpg' },
            { id: 'rD8k_5f0cWc', title: 'MAKE (INTEGROMAT) TUTORIAL PARA INICIANTES (COMPLETO)', duration: '50:15', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/rD8k_5f0cWc/hqdefault.jpg' },
            { id: 'h_fXz6b6fQ0', title: 'TUTORIAL ZAPIER PARA INICIANTES', duration: '15:21', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/h_fXz6b6fQ0/hqdefault.jpg' },
            { id: 'd-5W2aF-09g', title: 'O que é AUTOMAÇÃO DE MARKETING e COMO FAZER?', duration: '9:33', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/d-5W2aF-09g/hqdefault.jpg' },
            { id: 'y9y_Z9v_fJ0', title: 'Lovable Automação - Apresentação da Ferramenta', duration: '4:20', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/y9y_Z9v_fJ0/hqdefault.jpg' },
            { id: 'XoezG6P-Y3o', title: 'Como Automatizar o WHATSAPP com N8N (Guia Completo)', duration: '35:28', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/XoezG6P-Y3o/hqdefault.jpg' },
            { id: 'fFWHkOmLpEw', title: 'As 10 Melhores Ferramentas de Automação para Empresas', duration: '12:55', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/fFWHkOmLpEw/hqdefault.jpg' },
            { id: '7oJcybPJb6s', title: 'Automação de Tarefas com Python (Tutorial para Iniciantes)', duration: '28:10', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/7oJcybPJb6s/hqdefault.jpg' },
            { id: 'l2kOqG-e68o', title: 'Como Integrar o CHATGPT com PLANILHAS GOOGLE (via Make)', duration: '19:47', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/l2kOqG-e68o/hqdefault.jpg' },
            { id: '3D3j2bBKFrM', title: 'O que é RPA (Robotic Process Automation)?', duration: '8:15', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/3D3j2bBKFrM/hqdefault.jpg' },
            { id: 'Vd4i4b2P0e0', title: '5 Automações no ZAPIER que vão SALVAR seu TEMPO', duration: '10:30', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Vd4i4b2P0e0/hqdefault.jpg' },
            { id: 'z1m_X-Ci0A8', title: 'Como usar a API do OPENAI no N8N (Passo a Passo)', duration: '22:04', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/z1m_X-Ci0A8/hqdefault.jpg' },
            { id: 'b_fLp0k-9I4', title: 'ManyChat para Iniciantes: Tutorial de Automação no Messenger', duration: '33:19', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/b_fLp0k-9I4/hqdefault.jpg' },
            { id: 'W0QkbuWf_3g', title: 'Automação de E-mail Marketing com ActiveCampaign', duration: '25:46', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/W0QkbuWf_3g/hqdefault.jpg' },
            { id: 'Y7k3c3P4z4Q', title: 'Criando um DASHBOARD AUTOMATIZADO no Google Data Studio', duration: '41:17', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Y7k3c3P4z4Q/hqdefault.jpg' },
        ],
    },
    {
        id: 'academia-fitness',
        title: 'Academia e Fitness',
        description: 'Treino, nutrição, ganho de massa e emagrecimento para resultados reais',
        icon: 'Dumbbell',
        color: 'yellow',
        videos: [
            { id: '8-x8zDPa2pM', title: 'COMO MONTAR UM TREINO DE HIPERTROFIA COMPLETO (DO ZERO)', duration: '17:33', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/8-x8zDPa2pM/hqdefault.jpg' },
            { id: 'o65g14-VSvY', title: 'COMO GANHAR MASSA MUSCULAR? (GUIA DEFINITIVO)', duration: '20:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/o65g14-VSvY/hqdefault.jpg' },
            { id: 'uP1o2o7uC1o', title: 'DIETA PARA EMAGRECER E PERDER BARRIGA RÁPIDO', duration: '12:12', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/uP1o2o7uC1o/hqdefault.jpg' },
            { id: 'lT9sY4j8aZc', title: 'TREINO ABC: O GUIA COMPLETO', duration: '10:45', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/lT9sY4j8aZc/hqdefault.jpg' },
            { id: '3D5g7_Wd23w', title: 'CALISTENIA PARA INICIANTES: Como Começar do Zero', duration: '13:02', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/3D5g7_Wd23w/hqdefault.jpg' },
            { id: 'tN--32gwR8c', title: 'JEJUM INTERMITENTE: GUIA COMPLETO para INICIANTES', duration: '15:40', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/tN--32gwR8c/hqdefault.jpg' },
            { id: 'B8a_gQ9yofQ', title: 'Os 5 MELHORES SUPLEMENTOS para GANHAR MASSA MUSCULAR', duration: '14:21', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/B8a_gQ9yofQ/hqdefault.jpg' },
            { id: 'Rzl_v2gI-bw', title: 'Como fazer AGACHAMENTO LIVRE (execução correta)', duration: '9:58', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Rzl_v2gI-bw/hqdefault.jpg' },
            { id: 'UIt3bY-M-gE', title: 'Treino de PEITO COMPLETO para HIPERTROFIA', duration: '11:35', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/UIt3bY-M-gE/hqdefault.jpg' },
            { id: 'sWj5sEMdM_A', title: 'Os 7 PIORES ERROS que te IMPEDEM de EMAGRECER', duration: '13:08', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/sWj5EMdM_A/hqdefault.jpg' },
            { id: 'Yq13xKCHy8s', title: 'Dieta FLEXÍVEL e MACROS (Guia para Iniciantes)', duration: '18:55', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Yq13xKCHy8s/hqdefault.jpg' },
            { id: 'jQk8f8-yA_Q', title: 'Como Fazer a DIETA DO GUERREIRO para Queimar Gordura', duration: '10:19', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/jQk8f8-yA_Q/hqdefault.jpg' },
            { id: '4maLMHi-4-o', title: 'Treino de COSTAS e BÍCEPS COMPLETO', duration: '12:47', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/4maLMHi-4-o/hqdefault.jpg' },
            { id: 'TKOtB0gPAAM', title: 'Mobilidade e Alongamento: QUAL A DIFERENÇA?', duration: '8:42', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/TKOtB0gPAAM/hqdefault.jpg' },
            { id: 'B-zV1G8tKsw', title: 'Como Calcular suas CALORIAS e MACROS (Passo a Passo)', duration: '22:16', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/B-zV1G8tKsw/hqdefault.jpg' },
        ],
    },
    {
        id: 'psicologia-desenvolvimento',
        title: 'Psicologia e Desenvolvimento',
        description: '48 Leis do Poder, estratégias de guerra, mentalidade vencedora e desenvolvimento pessoal',
        icon: 'Heart',
        color: 'rose',
        videos: [
            { id: 'ACJTb15p44k', title: 'AS 48 LEIS DO PODER (RESUMO ANIMADO)', duration: '19:58', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/ACJTb15p44k/hqdefault.jpg' },
            { id: 'ZyeZf4f-b-w', title: 'ESTOICISMO: A ARTE DE VIVER (GUIA PARA INICIANTES)', duration: '11:23', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/ZyeZf4f-b-w/hqdefault.jpg' },
            { id: 'Q8fkplMhOug', title: 'A ARTE DA GUERRA - Sun Tzu (Resumo)', duration: '8:41', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Q8fkplMhOug/hqdefault.jpg' },
            { id: 'm0kL1vNUlAY', title: 'INTELIGÊNCIA EMOCIONAL por Daniel Goleman (Resumo Animado)', duration: '10:01', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/m0kL1vNUlAY/hqdefault.jpg' },
            { id: 'k4pGe-5z7sU', title: 'O PODER DO HÁBITO (Resumo Animado)', duration: '9:07', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/k4pGe-5z7sU/hqdefault.jpg' },
            { id: 'dautg2-CF3E', title: 'As LEIS DA NATUREZA HUMANA por Robert Greene (Resumo)', duration: '15:25', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/dautg2-CF3E/hqdefault.jpg' },
            { id: 'nEa5k-oY22A', title: 'Como ter uma MENTALIDADE VENCEDORA (Kobe Bryant)', duration: '12:38', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/nEa5k-oY22A/hqdefault.jpg' },
            { id: 'B4a7JNAUexA', title: 'Comunicação ASSERTIVA: O que é e como desenvolver', duration: '10:59', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/B4a7JNAUexA/hqdefault.jpg' },
            { id: 't2z-30yO-wI', title: 'O EGO É SEU INIMIGO por Ryan Holiday (Resumo)', duration: '11:47', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/t2z-30yO-wI/hqdefault.jpg' },
            { id: '8K0He7o-jcM', title: 'Como VENCER a PROCRASTINAÇÃO (Método Comprovado)', duration: '14:03', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/8K0He7o-jcM/hqdefault.jpg' },
            { id: 'w4e22Db3M5M', title: 'O Poder do SUBCONSCIENTE por Joseph Murphy', duration: '13:16', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/w4e22Db3M5M/hqdefault.jpg' },
            { id: '7Lu-0-hP8fo', title: 'Como LER PESSOAS (Psicologia e Linguagem Corporal)', duration: '9:54', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/7Lu-0-hP8fo/hqdefault.jpg' },
            { id: 't4z38j48svA', title: 'O Obstáculo é o Caminho: A Filosofia do Estoicismo', duration: '11:11', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/t4z38j48svA/hqdefault.jpg' },
            { id: 'Yw7kvjYYE-A', title: 'MINDSET: A Nova Psicologia do Sucesso (Resumo Animado)', duration: '10:28', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/Yw7kvjYYE-A/hqdefault.jpg' },
            { id: 'ySg-53m50g4', title: 'Como ser mais CONFIANTE (e menos inseguro)', duration: '12:45', platform: 'youtube', thumbnailUrl: 'https://i.ytimg.com/vi/ySg-53m50g4/hqdefault.jpg' },
        ],
    }
];
