// Fix: Consolidate all IconName definitions here to serve as the single source of truth and remove circular dependencies.
// All icon names are now defined in this one place.
export type IconName = 
  // Base Icons
  'Fire' | 'Chart' | 'Heart' | 'ChevronLeft' | 'Play' | 'Plus' | 'Check' | 'Share' |
  // App-specific Icons from original type
  'Dumbbell' | 'Wrench' | 'Cart' | 'Dollar' | 'Brain' | 'X' | 'Send' | 'Gear' | 'UsersGroup' | 'Upload' | 'BookOpen' | 'Download' | 'Pencil' | 'Pause' | 'SkipBack' | 'SkipForward' | 'Trash' | 'Search' | 'Film' | 'Sparkles' | 'Info' | 'VolumeUp' | 'VolumeOff';


export interface User {
  name: string;
  password?: string;
  avatarUrl: string; // Added for profile pictures
}

export interface OnlineUser {
    name: string;
    avatarUrl: string;
}

export interface Video {
  id: string; // youtube video ID
  title: string;
  duration: string; // e.g. "10:32"
  thumbnailUrl: string;
  platform: 'youtube';
}

export interface LearningCategory {
  id: string; // e.g. "frontend-dev"
  title: string;
  description: string;
  icon: IconName;
  color: 'red' | 'orange' | 'green' | 'cyan' | 'blue' | 'indigo' | 'yellow' | 'rose';
  videos: Video[];
}

export interface NextVideoInfo {
  video: Video;
  category: LearningCategory;
}

export interface Chapter {
    title: string;
    content: string;
    imageUrl?: string;
    icon?: IconName;
}

export interface Project {
    id:string;
    name: string; // Ebook title
    introduction: string;
    chapters: Chapter[];
    conclusion: string;
    createdBy: string;
    avatarUrl: string;
    createdAt: number;
    coverImageUrl?: string; // URL for the AI-generated cover image
    // --- New Fields for Collaboration & Monetization ---
    collaborators?: string[]; // Array of user names
    status?: 'draft' | 'published';
    price?: number;
    publicDescription?: string;
}

export interface ProjectGenerationConfig {
    topic: string;
    chapters: number;
}

export interface QuizQuestion {
    question: string;
    options: string[];
    correctAnswer: string;
}

export interface VideoScene {
    narration: string;
    prompt: string;
}

export interface VideoScript {
    scenes: VideoScene[];
    fullNarrationScript: string;
}

// --- New Types for Short Form Video ---
export interface ShortFormScene {
    narration: string;
    imagePrompt: string; // The prompt generated by the first LLM call
    imageUrl?: string; // The final image URL from the Imagen model
}

export interface ShortFormVideoScript {
    hook: string; // Catchy intro line
    scenes: ShortFormScene[];
    cta: string; // Call to action
    musicSuggestion: string; // Keywords for music style
    fullNarrationAudioUrl?: string; // Data URL for the generated TTS audio
}


export interface SocialMediaIdea {
    title: string;
    script: string;
    audio: string;
}

export interface ChatMessage {
    role: 'user' | 'model';
    text: string;
}

export interface MeetingMessage {
    id:string;
    user: string;
    text: string;
    timestamp: string;
    avatarUrl: string; // Added for profile pictures
}

export interface Song {
  id: string;
  title: string;
  artist: string;
  url: string;
  storagePath: string; // Full path in Firebase Storage for deletion
}

export interface YouTubeTrack {
  id: string;
  title: string;
  artist: string;
  thumbnailUrl: string;
}

export interface YouTubePlaylist {
  id: string;
  title: string;
  thumbnailUrl: string;
  videoCount: number;
  uploaderName: string;
}

export interface YouTubeChannel {
  id: string;
  name: string;
  thumbnailUrl: string;
  description?: string;
}

export interface Notification {
    type: 'error' | 'info';
    message: string;
}

export interface RadioState {
  id?: number; // Should always be 1
  current_track_id: string | null;
  is_playing: boolean;
  seek_timestamp: number; // timestamp of last state change
  track_progress_on_seek: number; // track's currentTime at the time of the state change
  updated_by: string; // user who made the change
}
export interface Slide {
  title: string;
  content: string[]; // Bullet points
  imagePrompt: string; // Prompt for the slide's background image
}